### ISSUE TITLE
[Anon] Bug report: Orks.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#140] opened 2020-09-08 22:51 UTC
**File:** Orks.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Kustom Stompa standard weapons are incomplete. Gaze of Mork, MegaKlaw, Big Shootas are missing.

**Comment by Mad-Spy** [comment] 2021-01-12 16:36
Duplicate of #138

**Closed as completed by Mad-Spy** 2021-01-12 16:36 UTC
