### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Astartes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-apocalypse#47] opened 2019-08-03 10:04 UTC
**File:** Imperium - Adeptus Astartes.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** Space marine flyers are mixed. Stormraven and other gunships share stats.

**Comment by DrTobogganMD** [comment] 2019-08-03 12:23
Duplicate of #46

**Closed as completed by DrTobogganMD** 2019-08-03 12:23 UTC
Labels: ✔ Resolution: Duplicate
